<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Lab2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>85c9b4f8-051a-46f7-841a-5dcedaf04311</testSuiteGuid>
   <testCaseLink>
      <guid>3d5169ba-37fb-4084-91fc-f300991d5cf3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Lab2_001</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39e4eb68-f396-4a51-9e60-076871387761</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e009cb5a-1d20-4cea-ae96-2f977444c8b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f78a4b19-8a2a-488b-a813-1ae79dd6a87f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b6292f8-d9cc-4184-a1b0-73451b8f8d56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Lab2_002</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05c68235-7154-4dc4-a19e-93047e89d11e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2479c928-89a8-4768-8565-81367cee6a22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6924b959-859f-4335-be7a-d01e387bb1a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d74d4bcc-2b26-4e9c-a448-1670804e7435</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Lab2_003</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb9e875e-9da0-4e1d-8880-105d248e5a46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6dfd0d9-1ca4-44be-9e8f-f8788e2ea2bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ac38b5f-2f58-4b16-8fd6-017a23e9dcd6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ed35cea-a655-4d66-9f08-e1a367d47c01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Lab2_004</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8165a3a6-03e6-408a-b6a9-c92cfdac43be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a7e30e5-9038-4175-93c8-d23481fb67aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0c2113d-5a44-49c5-b66a-bb13be2bf4c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae1087d3-1759-4d2e-9f96-6bad7e4ef2ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Lab2_005</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>753dbabc-905f-49dc-a689-f000cda54af6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
